version: '3'

services:
  gatsby:
    image: gatsbyjs/gatsby:$GATSBYJS_TAG
    container_name: "${PROJECT_NAME}_gatsby"
    volumes:
      # - ./site:$GATSBYJS_SITE_PATH
      # For macOS users 
      - ./site:$GATSBYJS_SITE_PATH:cached # User-guided caching
    environment:
      PUBLIC_PATH: $GATSBYJS_PUBLIC_PATH
    labels:
      - 'traefik.backend=gatsby'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   
